### ISSUE TITLE
Working with local firehose

### ISSUE THREAD

**Issue by adapt7** [0xpcut/solana-indexer#5]
Hi @0xpcut 

I set up my local firehose indexer:

firecore version 1.8.0 (Commit 75951cb, Built 2025-02-25T18:11:14Z)
firesol  1.1.3

Standard firehhose-solana.yaml:

```
start:
  args:
  - reader-node
  - merger
  - relayer
  - firehose
  - substreams-tier1
  - substreams-tier2
  flags:
    log-format: text
    log-to-file: false
    advertise-chain-name: solana-mainnet
    common-first-streamable-block: 322938838
    reader-node-path: "firesol"
    reader-node-arguments: |
      fetch
      rpc
      322938838
      --endpoints http://127.0.0.1:8765
      --state-dir
      {data-dir}/reader/data
    substreams-tier1-block-type: "sf.solana.type.v1.Block"
    substreams-tier1-grpc-listen-addr: :9000
```

The simple substream works fine:

`substreams run -e localhost:9000 --plaintext https://github.com/streamingfast/substreams-sink-noop/raw/develop/substreams-head-tracker/substreams-head-tracker-v1.0.0.spkg -s 322938838 map_blocks`

The solana-indexer database_changes that works great with mainnet.sol.streamingfast.io:443 endpoint, is failing locally:

`wasm execution failed deterministically: panic in the wasm: "called `Option::unwrap()` on a `None` value" git/checkouts/substreams-solana-utils-23aabdc1dc965db7/2928e7e/src/instruction.rs:124:`

What am I missing here? Do I need any specific binaries versions or maybe add something to the configs?
